/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/base.glb 
*/

import { useGLTF } from "@react-three/drei";

export function Base(props) {
  const { nodes, materials } = useGLTF("./models/base.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.floor}
        position={[0, 0.054, 0]}
        scale={[10.962, 0.001, 10.962]}
      />
      <group position={[0, 0.006, 0]} scale={[1.237, 0.057, 1.237]}>
        <mesh
          geometry={nodes.Cylinder004.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Cylinder004_1.geometry}
          material={materials["arceau.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/base.glb");

export default Base;
